### ISSUE TITLE
setup travis

### ISSUE THREAD

**Issue by lsmith77** [solutionDrive/SyliusImportExportPlugin#10]

**Comment by solutionDrive-Alt** [comment]
At the moment we have a problem with the sqlite-Database and travis.

[broken build](https://travis-ci.org/solutionDrive/SyliusImportExportPlugin/builds/295526295#L513)

**Comment by solutionDrive-Alt** [comment]
Travis is running now correctly. Problem was a missing folder in the repository, because of a missing .gitkeep-file
