### ISSUE TITLE
choose a namespace

### ISSUE THREAD

**Issue by lsmith77** [solutionDrive/SyliusImportExportPlugin#12]
right now the classes use `FriendsOfSylius` as the namespace while the services/command uses `sylius` as a namespace. we should probably clean that up?

also relates to the question where this plugin should live .. ie. on the `FriendsOfSylius` org or on the `Sylius` org on github

**Comment by lsmith77** [comment]
relates to https://github.com/Sylius/Sylius/issues/8848

**Comment by lsmith77** [comment]
I guess the decision is more or less to keep things as is and move this Bundle to the `FriendsOfSylius` org. see also https://github.com/friendsofsylius/SyliusGoose/issues/6

**Comment by solutionDrive-Alt** [comment]
Agreed. :-)

**Comment by lsmith77** [comment]
cc @bitbager

**Comment by bitbager** [comment]
@lsmith77, I've created a repository for the organization - https://github.com/friendsofsylius/SyliusImportExportPlugin. I've also given you the admin privileges for this repo. Good luck! 🙂

**Comment by lsmith77** [comment]
my life motto: luck is a skill :)
